<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion>
<parent><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId><version>4.1.1</version><relativePath/></parent>
<groupId>io.portfolio</groupId><artifactId>java-senior-platform</artifactId><version>1.0.0</version><packaging>pom</packaging>
<properties><java.version>25</java.version><tomcat.version>11.0.25</tomcat.version><rabbit-amqp-client.version>5.33.1</rabbit-amqp-client.version><project.build.sourceEncoding>UTF-8</project.build.sourceEncoding></properties>
<modules><module>domain</module><module>platform</module><module>ledger-service</module><module>audit-service</module></modules>
<build><plugins><plugin><groupId>com.diffplug.spotless</groupId><artifactId>spotless-maven-plugin</artifactId><version>3.10.2</version><configuration><java><googleJavaFormat><version>1.36.1</version></googleJavaFormat></java></configuration></plugin></plugins><pluginManagement><plugins><plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId></plugin></plugins></pluginManagement></build></project>
