import {test,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {readFileSync} from 'node:fs';
import {resolve} from 'node:path';
const env=Object.fromEntries(readFileSync(resolve('..','.env'),'utf8').split(/\r?\n/).filter(l=>l.includes('=')).map(l=>[l.slice(0,l.indexOf('=')),l.slice(l.indexOf('=')+1)]));
test('login, create account, deposit, reject invalid input and view audit',async({page},testInfo)=>{
 await page.goto('/');
 await expect(page.getByRole('button',{name:/Sign in securely/})).toBeVisible();
 const landing=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
 expect(landing.violations).toEqual([]);
 await page.getByRole('button',{name:/Sign in securely/}).click();
 await page.getByLabel('Username or email').fill('demo');
 await page.getByLabel('Password',{exact:true}).fill(env.DEMO_PASSWORD);
 await page.getByRole('button',{name:'Sign In',exact:true}).click();
 await expect(page.getByRole('button',{name:'Sign out'})).toBeVisible();
 const name='Browser '+testInfo.project.name+' '+Date.now();
 await page.getByLabel('Account name',{exact:true}).fill(name);
 await page.getByRole('button',{name:'Create account',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('Account created');
 await page.getByLabel('Amount (USD)',{exact:true}).fill('25.50');
 await page.getByLabel('Description',{exact:true}).fill('Browser deposit');
 await page.getByRole('button',{name:'Record movement',exact:true}).click();
 await expect(page.getByRole('status')).toContainText('Movement recorded');
 await expect(page.getByRole('table')).toContainText('Browser deposit');
 await page.getByLabel('Amount (USD)',{exact:true}).fill('1.001');
 await page.getByLabel('Description',{exact:true}).fill('Invalid precision');
 await page.getByRole('button',{name:'Record movement',exact:true}).click();
 await expect(page.getByRole('alert')).toContainText('two decimal places');
 const workspace=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();
 expect(workspace.violations).toEqual([]);
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.screenshot({path:testInfo.outputPath('accounts.png'),fullPage:true});
 await page.getByRole('button',{name:'Audit trail',exact:false}).click();
 await expect.poll(async()=>{await page.getByRole('button',{name:'Refresh data'}).click();return page.getByRole('table').count();},{timeout:20000}).toBe(1);
 await expect(page.getByRole('table')).toContainText('25.50');
 await page.getByRole('button',{name:'Sign out'}).click();
 await expect(page.getByRole('button',{name:/Sign in securely/})).toBeVisible();
});
